
name: Trigger Repos

on:
  push:
    branches: [main, master]
    paths:
      - 'themes/*'
      - 'fonts/*'
  workflow_dispatch:
  
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pages Publish in other Repos
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.Disbatch_Action }}" \
            https://api.github.com/repos/ch-sz-geo/T000_TestRepoWED/dispatches \
            -d '{"event_type":"run-external-workflow","client_payload":{"ref":"main"}}'
