
name: Trigger Repos

on:
  workflow_run: 
    workflows: [pages-build-deployment]
    types:
      - completed
    branches: [main, master]
    
  workflow_dispatch:
  
jobs:
  post_deploy:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Pages Publish in other Repos
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.Disbatch_Action }}" \
            https://api.github.com/repos/ch-sz-geo/T000_TestRepoWED/dispatches \
            -d '{"event_type":"run-external-workflow","client_payload":{"ref":"main"}}'
